version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  task-app:
    build: .
    container_name: task-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  mongo_data: