pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/tejagandham18/Devops.git'
            }
        }

        stage('Code Quality Check') {
            steps {
                bat 'docker run --rm -v %cd%:/app -w /app python:3.13 pip install flake8'
                bat 'docker run --rm -v %cd%:/app -w /app python:3.13 flake8 app.py'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'docker run --rm -v %cd%:/app -w /app python:3.13 pip install -r requirements.txt pytest'
                bat 'docker run --rm -v %cd%:/app -w /app python:3.13 pytest'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker compose build'
            }
        }

        stage('Run Containers') {
            steps {
                bat 'docker compose up -d'
            }
        }
    }
}